name: Publish extension or native host
run-name: ${{ github.actor }} is publishing a new version of the extension or the native host
on: 
  push:
    branches:
      - main
      - release/**
      - gh_action
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🔎 The name of your branch is ${{ github.ref }}"
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Fetch old commit
        run: git fetch origin ${{ github.event.before }}
      - name: Determine changes
        id: changes
        run: |
          git diff --name-only HEAD ${{ github.event.before }} >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
